In [31]:
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem.snowball import SnowballStemmer
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk
import pandas as pd

nltk.download('punkt')
nltk.download('stopwords')

categories = ['comp.os.ms-windows.misc', 'sci.space','rec.sport.baseball']

print(categories)

news_data = fetch_20newsgroups(subset='train', categories=categories)

print(type(news_data))

popped_data1Value = news_data.popitem()[0]
print(popped_data1Value)

print("Values 2")

popped_data2Value = news_data.popitem()[1]
print(popped_data2Value)

df = news_data
news_data_df = pd.DataFrame(data= df.data)    

news_data_df.sample(50)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/williamseong/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/williamseong/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['comp.os.ms-windows.misc', 'sci.space', 'rec.sport.baseball']
<class 'sklearn.utils.Bunch'>
DESCR
Values 2
[2 0 0 ... 2 1 2]

                                                      0
1738  From: 18084TM@msu.edu (Tom)\nSubject: Nasa (di...
21    From: jdnicoll@prism.ccs.uwo.ca (James Davis N...
1639  From: nsmca@aurora.alaska.edu\nSubject: Re: Ec...
133   From: adriene_nazaretian@qm.yale.edu (Adriene ...
1071  From: wallacen@CS.ColoState.EDU (nathan wallac...
1144  From: eder@hsvaic.boeing.com (Dani Eder)\nSubj...
538   From: sepinwal@mail.sas.upenn.edu (Alan Sepinw...
1206  From: nsmca@aurora.alaska.edu\nSubject: $1bil ...
281   From: debrown@hubcap.clemson.edu (David E. Bro...
8     From: wmiler@nyx.cs.du.edu (Wyatt Miler)\nSubj...
114   From: jafoust@cco.caltech.edu (Jeff Foust)\nSu...
352   From: tkelso@afit.af.mil (TS Kelso)\nSubject: ...
1489  From: jhunter@mta.ca (John Hunter)\nSubject: W...
1460  From: gwh@soda.berkeley.edu (George William He...
83    From: spira@panix.com (Greg Spira)\nSubject: R...
422   From: ak333@cleveland.Freenet.Edu (Martin Lins...
107   From: thomas@datamark.co.nz (Thomas Beagle)\nS...
516   From: jenkinch@ccmail.orst.edu\nSubject: Re: A...
1665  Subject: Re: WINBENCH 3.11 help -- graphics co...
174   From: dbarker@spang.Camosun.BC.CA (Deryk Barke...
1156  From: byab314@chpc.utexas.edu (Srinivas Bettad...
756   From: dkeisen@leland.Stanford.EDU (Dave Eisen)...
1461  From: dbm0000@tm0006.lerc.nasa.gov (David B. M...
690   From: kjenks@gothamcity.jsc.nasa.gov\nSubject:...
989   From: cs902060@ariel.yorku.ca (GEOFFREY E DIAS...
240   From: kudla@acm.rpi.edu (Robert Kudla)\nSubjec...
1077  Subject: Re: Gamma Ray Bursters.  Where are th...
1592  From: mike@cunixf.cc.columbia.edu (Michael Che...
892   From: uck@netcom.com (Tom Chamberlain)\nSubjec...
1407  From: thf2@kimbark.uchicago.edu (Ted Frank)\nS...
750   From: wilbanks@spot.Colorado.EDU (Kokopeli)\nS...
604   From: news@leland.Stanford.EDU (Mr News)\nSubj...
894   From: prb@access.digex.com (Pat)\nSubject: Re:...
71    From: glover@casbah.acns.nwu.edu (Eric Glover)...
1723  From: traven@pitt.edu (Neal Traven)\nSubject: ...
120   From: jtchern@ocf.berkeley.edu (Joseph Hernand...
501   From: paula@koufax.cv.hp.com (Paul Andresen)\n...
798   From: erics@netcom.com (Eric Smith)\nSubject: ...
1564  From: herrod@CS.Stanford.EDU (Stephen Herrod)\...
1405  From: dwarner@journalism.indiana.edu (David J....
293   From: tedward@cs.cornell.edu (Edward [Ted] Fis...
1374  From: Chera Bekker <bekker@tn.utwente.nl>\nSub...
433   From: liuxu@vuse.vanderbilt.edu (Xudong Liu)\n...
110   Nntp-Posting-Host: 134.58.96.14\nFrom: wimvh@l...
225   From: dwarner@journalism.indiana.edu (David J....
1353  From: jxu@black.clarku.edu (Dark Wing Duck!!)\...
1422  From: John Lussmyer <dragon@angus.mi.org>\nSub...
678   From: jkatz@access.digex.com (Jordan Katz)\nSu...
32    From: servis@author.ecn.purdue.edu (Brian K Se...
430   From: taylor@mail  (Tim Taylor)\nSubject: Re: ...

In [38]:
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer

dataset = load_breast_cancer(as_frame=True)

dataset['data'].head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [41]:
dataset['target'].head()
# So these are the actual results, 0 means benign and 1 means malignant

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [42]:
dataset['target'].value_counts()
# These are the totals

1    357
0    212
Name: target, dtype: int64